package com.Otdescrption.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.Otdescrption.Dto.Cookie;
import com.Otdescrption.service.CookieService;

@RestController
@RequestMapping("/cookies")
public class CookieController {

	@Autowired
	private CookieService cookieService;

	@PutMapping("/update")
	public void updateCookies(@RequestBody List<Cookie> cookies ) {
		String accessToken="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Imp3dCJ9.eyJyb2xlIjoiQXBpIEtleSBVc2VyIiwiZGZkIjoidW5pbGV2ZXIubXkub25ldHJ1c3QuY29tIiwiYWFkIjoidW5pbGV2ZXIubXkub25ldHJ1c3QuY29tIiwidXNlcl9uYW1lIjoiZmI1MzAzMTI4ZWQ4NDUwMGI2YTY1YWFmNDAwMjhlNjVAYXBpLm9uZXRydXN0LmNvbSIsImxhbmd1YWdlSWQiOjEsInNlc3Npb25JZCI6IjYzZDZmZjVhLTdhNDMtNDkwYy04NDc2LTQ1OTk3YmZiMDU1NiIsInRlbmFudEd1aWQiOiJmYjUzMDMxMi04ZWQ4LTQ1MDAtYjZhNi01YWFmNDAwMjhlNjUiLCJjbGllbnRfaWQiOiI0ZWY0NmZhOWQxMjE0YzFhYWJjMGQxOWQ5Yjc2OGQyMiIsImRzYSI6InVuaWxldmVyLXByaXZhY3kubXkub25ldHJ1c3QuY29tIiwib3JnR3JvdXBJZCI6IjJmZDI4NmE2LThiNjQtNDA4MC04MmI3LThlMjU0OGEwZDI5NyIsIm9yZ0dyb3VwR3VpZCI6IjJmZDI4NmE2LThiNjQtNDA4MC04MmI3LThlMjU0OGEwZDI5NyIsIm90LXNjb3BlcyI6IkFETUlOLEFUVEFDSE1FTlQsQVRUQUNITUVOVF9SRUFELEJVTEtfRVhQT1JULENPT0tJRSxDT09LSUVfRlJFRSxDT09LSUVfUkVBRCxEU0FSX1JFQUQsRFNBUl9XUklURSxJTlRFR1JBVElPTl9KV0tTLElOVEVHUkFUSU9OUyxPUkdBTklaQVRJT04sU0NJTSxVU0VSIiwic2NvcGUiOltdLCJ0ZW5hbnRJZCI6MjI0LCJndWlkIjoiZjg0Y2IxOGYtODU1Zi00MzQ2LWFkNWMtODcxMThkMDYzZDI3IiwiZHBkIjoidW5pbGV2ZXItcHJpdmFjeS5teS5vbmV0cnVzdC5jb20iLCJleHAiOjE3NDY2MzU5MjUsImV4cGlyZXNfaW4iOjM2MDAsImp0aSI6Im5keTQ2SXlSSkRudkNadU42bHB2bUN4RjBYTSIsImVtYWlsIjoiZmI1MzAzMTI4ZWQ4NDUwMGI2YTY1YWFmNDAwMjhlNjVAYXBpLm9uZXRydXN0LmNvbSJ9.ffHDIuJg8J3iwJTLkR68Bg0Wqq03xUXzgf8Wv1due_JqcD5Dkv2hgnGeU9gHhRx6k889CyCQBSDHueSHSe4YRydKAmqrNcwf2JUnY7ls0UsbFjQ8GEoZZegcnqfv4pDR5xaP4bX5ocveSI4tLhcyqsltGHqv8H7ZO2xPFo-gpY_sjP4ypANNpBf_H__but4z9kfkrZUr2Tf1AzbxPQWbIcJWQkQK9o0w5hF9prnD5wy9eQU-HSPMl26k0c3pnJRCzjuGLJiiNo3Bb9mCkos0DmEhbjHC1QEzNP2-8iL7oyoJXLNCY7MyTpsn4Uwyvyj_AqAYcUcPl95fV1AkHNaFXg";
		for (Cookie cookie : cookies) {

			cookieService.updateCookieDescription(cookie, accessToken);

}
}
}
